### ISSUE TITLE
Possible to adjust keyframe?

### ISSUE THREAD

**Issue by vinesmsuic** [RuoyuFeng/CCEdit#6]
Hi, came across of this fascinating work. I wonder if the keyframe can be set as the first frame? It seems in the paper all the keyframes were the middle frame.

![image](https://github.com/user-attachments/assets/5eb916df-6238-4e4b-99a7-e5d21b45d79a)

![image](https://github.com/user-attachments/assets/f08d9760-46ab-4867-a0df-5bf4d508749a)

**Comment by vinesmsuic** [comment]
@RuoyuFeng From the code it seems the reference frame prior is applied across all time step
```python
elif args.prior_type == 'ref':
    prior = model.encode_first_stage(ref)
    prior = repeat(prior, 'b c h w -> b c t h w', t=num_keyframes)
```

But from the outputs it seems the reference image would 100% match the middle frame of the output. I wonder if this could be controlled such that we can apply the reference image into the first frame or the last frame?

**Comment by RuoyuFeng** [comment]
> @RuoyuFeng From the code it seems the reference frame prior is applied across all time step
> 
> ```python
> elif args.prior_type == 'ref':
>     prior = model.encode_first_stage(ref)
>     prior = repeat(prior, 'b c h w -> b c t h w', t=num_keyframes)
> ```
> 
> But from the outputs it seems the reference image would 100% match the middle frame of the output. I wonder if this could be controlled such that we can apply the reference image into the first frame or the last frame?

Thanks for your attention and question!

In our model, the reference frame is the middle frame. It's fixed since we trained the model in the manner of condition on the center frame. If you want to change the reference frame from middle into the first frame or the last frame. Fine-tune the model might be a promising way.
Besides, in my observation, the conditional reference frame will always be exactly the same as the corresponding frame in the output video (i.e., the middle frame). I think it's because the model learns a short cut to copy the reference frame into corresponding location in the output video.

**Comment by vinesmsuic** [comment]
Thanks for the insights!
